import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

// ──────────────────────────────────────────────
// Department bounding boxes (approx)
// ──────────────────────────────────────────────
const DEPARTMENTS = {
  'Vendée':             { south: 46.27, west: -2.40, north: 47.08, east: -0.54 },
  'Deux-Sèvres':       { south: 45.96, west: -0.73, north: 47.11, east: 0.24 },
  'Loire-Atlantique':   { south: 46.86, west: -2.56, north: 47.84, east: -0.92 },
  'Maine-et-Loire':     { south: 47.06, west: -1.35, north: 47.81, east: 0.24 },
  'Vienne':             { south: 46.06, west: -0.06, north: 47.18, east: 1.21 },
  'Charente':           { south: 45.19, west: -0.47, north: 46.14, east: 0.95 },
  'Charente-Maritime':  { south: 45.08, west: -1.56, north: 46.37, east: -0.06 },
}

// ──────────────────────────────────────────────
// Known navigable waterways with metadata
// ──────────────────────────────────────────────
interface RouteDefinition {
  name: string
  waterway: string
  type: 'river' | 'canal'
  difficulty: 'easy' | 'moderate'
  department: string
  putInLat: number
  putInLng: number
  putInDescription: string
  takeOutLat: number
  takeOutLng: number
  takeOutDescription: string
  distanceKm: number
  bestSeasonNotes: string
  hubeauStationCode?: string
  description?: string
}

const CURATED_ROUTES: RouteDefinition[] = [
  // ── Charente ──
  {
    name: 'Charente — Angoulême to Châteauneuf',
    waterway: 'Charente',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente',
    putInLat: 45.6486,
    putInLng: 0.1560,
    putInDescription: 'Angoulême — base nautique',
    takeOutLat: 45.6019,
    takeOutLng: -0.0528,
    takeOutDescription: 'Châteauneuf-sur-Charente — slipway',
    distanceKm: 28,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'R3100010',
    description: 'Classic Charente section through vineyards. Flat water, several weirs with portage.',
  },
  {
    name: 'Charente — Jarnac to Cognac',
    waterway: 'Charente',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente',
    putInLat: 45.6813,
    putInLng: -0.1724,
    putInDescription: 'Jarnac — quai de la Charente',
    takeOutLat: 45.6958,
    takeOutLng: -0.3293,
    takeOutDescription: 'Cognac — parc François Ier',
    distanceKm: 18,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'R3140010',
    description: 'Gentle paddle past cognac houses. Flat, well-maintained towpath for shuttle.',
  },
  {
    name: 'Charente — Cognac to Saintes',
    waterway: 'Charente',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente-Maritime',
    putInLat: 45.6958,
    putInLng: -0.3293,
    putInDescription: 'Cognac — parc François Ier',
    takeOutLat: 45.7467,
    takeOutLng: -0.6324,
    takeOutDescription: 'Saintes — quai de Verdun',
    distanceKm: 35,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'R4050010',
    description: 'Long but flat section of the Charente. Can be split over two days.',
  },

  // ── Charente-Maritime ──
  {
    name: 'Charente — Saintes to Saint-Savinien',
    waterway: 'Charente',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente-Maritime',
    putInLat: 45.7467,
    putInLng: -0.6324,
    putInDescription: 'Saintes — quai de Verdun',
    takeOutLat: 45.8794,
    takeOutLng: -0.6821,
    takeOutDescription: 'Saint-Savinien — port',
    distanceKm: 30,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'R4050010',
    description: 'Tidal from Saint-Savinien. Plan around tides for the last stretch.',
  },
  {
    name: 'Boutonne — Saint-Jean-d\'Angély to Carillon',
    waterway: 'Boutonne',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente-Maritime',
    putInLat: 45.9420,
    putInLng: -0.5205,
    putInDescription: 'Saint-Jean-d\'Angély — base de canoë',
    takeOutLat: 45.9626,
    takeOutLng: -0.6199,
    takeOutDescription: 'Carillon — pont',
    distanceKm: 12,
    bestSeasonNotes: 'April to September',
    description: 'Quiet tributary of the Charente. Sheltered, tree-lined, great for beginners.',
  },
  {
    name: 'Seudre — Saujon meander',
    waterway: 'Seudre',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente-Maritime',
    putInLat: 45.6730,
    putInLng: -0.9254,
    putInDescription: 'Saujon — pont de la Seudre',
    takeOutLat: 45.6730,
    takeOutLng: -0.9254,
    takeOutDescription: 'Saujon — pont de la Seudre (loop)',
    distanceKm: 8,
    bestSeasonNotes: 'May to September',
    description: 'Short loop through salt marshes. Check tide times — tidal influence.',
  },

  // ── Sèvre Niortaise / Marais Poitevin ──
  {
    name: 'Sèvre Niortaise — Niort to Magné',
    waterway: 'Sèvre Niortaise',
    type: 'river',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.3230,
    putInLng: -0.4644,
    putInDescription: 'Niort — quai de la Préfecture',
    takeOutLat: 46.3078,
    takeOutLng: -0.5350,
    takeOutDescription: 'Magné — embarcadère',
    distanceKm: 10,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'L8100010',
    description: 'Gateway to the Marais Poitevin. Easy urban-to-rural paddle.',
  },
  {
    name: 'Marais Poitevin — Coulon canals',
    waterway: 'Marais Poitevin',
    type: 'canal',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.3211,
    putInLng: -0.5843,
    putInDescription: 'Coulon — embarcadère principal',
    takeOutLat: 46.3211,
    takeOutLng: -0.5843,
    takeOutDescription: 'Coulon — embarcadère (loop)',
    distanceKm: 8,
    bestSeasonNotes: 'April to October',
    description: 'Classic Green Venice loop through tree-canopied canals. Very sheltered, flat water.',
  },
  {
    name: 'Marais Poitevin — Arçais circuit',
    waterway: 'Marais Poitevin',
    type: 'canal',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.2947,
    putInLng: -0.6835,
    putInDescription: 'Arçais — embarcadère du port',
    takeOutLat: 46.2947,
    takeOutLng: -0.6835,
    takeOutDescription: 'Arçais — embarcadère (loop)',
    distanceKm: 6,
    bestSeasonNotes: 'April to October',
    description: 'Quieter alternative to Coulon. Narrow canals through the Green Venice.',
  },
  {
    name: 'Marais Poitevin — La Garette loop',
    waterway: 'Marais Poitevin',
    type: 'canal',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.2840,
    putInLng: -0.6200,
    putInDescription: 'La Garette — embarcadère',
    takeOutLat: 46.2840,
    takeOutLng: -0.6200,
    takeOutDescription: 'La Garette — embarcadère (loop)',
    distanceKm: 7,
    bestSeasonNotes: 'April to October',
    description: 'Quiet canals south of the main Marais. Less crowded, more wildlife.',
  },
  {
    name: 'Autise — Saint-Hilaire-la-Palud',
    waterway: 'Autise',
    type: 'river',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.2700,
    putInLng: -0.7200,
    putInDescription: 'Saint-Hilaire-la-Palud — pont',
    takeOutLat: 46.2950,
    takeOutLng: -0.6900,
    takeOutDescription: 'Le Vanneau — pont',
    distanceKm: 5,
    bestSeasonNotes: 'April to September',
    description: 'Tiny Marais river flowing through wet meadows. Very peaceful.',
  },

  // ── Vendée ──
  {
    name: 'Sèvre Niortaise — Maillezais to Damvix',
    waterway: 'Sèvre Niortaise',
    type: 'river',
    difficulty: 'easy',
    department: 'Vendée',
    putInLat: 46.3726,
    putInLng: -0.7389,
    putInDescription: 'Maillezais — port',
    takeOutLat: 46.3230,
    takeOutLng: -0.7400,
    takeOutDescription: 'Damvix — port',
    distanceKm: 9,
    bestSeasonNotes: 'April to October',
    description: 'Vendée side of the Marais Poitevin. Abbey views, flat, scenic.',
  },
  {
    name: 'Marais Poitevin — Maillé canals',
    waterway: 'Marais Poitevin',
    type: 'canal',
    difficulty: 'easy',
    department: 'Vendée',
    putInLat: 46.3900,
    putInLng: -0.7900,
    putInDescription: 'Maillé — embarcadère',
    takeOutLat: 46.3900,
    takeOutLng: -0.7900,
    takeOutDescription: 'Maillé — embarcadère (loop)',
    distanceKm: 7,
    bestSeasonNotes: 'April to October',
    description: 'Northern Marais canals. Very quiet, rich birdlife.',
  },
  {
    name: 'Lac de Mervent-Vouvant',
    waterway: 'Mervent',
    type: 'river',
    difficulty: 'easy',
    department: 'Vendée',
    putInLat: 46.5260,
    putInLng: -0.7520,
    putInDescription: 'Base de loisirs de Mervent',
    takeOutLat: 46.5260,
    takeOutLng: -0.7520,
    takeOutDescription: 'Base de loisirs (loop)',
    distanceKm: 5,
    bestSeasonNotes: 'May to September',
    description: 'Forest lake in Mervent-Vouvant. Calm water, wooded shoreline, no current.',
  },
  {
    name: 'Lay — Mareuil-sur-Lay',
    waterway: 'Lay',
    type: 'river',
    difficulty: 'moderate',
    department: 'Vendée',
    putInLat: 46.5356,
    putInLng: -1.2207,
    putInDescription: 'Mareuil-sur-Lay — base nautique',
    takeOutLat: 46.4900,
    takeOutLng: -1.2500,
    takeOutDescription: 'La Claye — pont',
    distanceKm: 12,
    bestSeasonNotes: 'April to September',
    description: 'Pleasant Vendée river with gentle current. A few riffles after rain.',
  },

  // ── Loire-Atlantique ──
  {
    name: 'Erdre — Nantes to Sucé-sur-Erdre',
    waterway: 'Erdre',
    type: 'river',
    difficulty: 'easy',
    department: 'Loire-Atlantique',
    putInLat: 47.2267,
    putInLng: -1.5508,
    putInDescription: 'Nantes — Port de la Tortière',
    takeOutLat: 47.3395,
    takeOutLng: -1.5260,
    takeOutDescription: 'Sucé-sur-Erdre — port',
    distanceKm: 16,
    bestSeasonNotes: 'All year',
    hubeauStationCode: 'M0400010',
    description: 'Called the most beautiful river in France. Wide, calm, tree-lined. Ideal for all levels.',
  },
  {
    name: 'Erdre — Sucé to Nort-sur-Erdre',
    waterway: 'Erdre',
    type: 'river',
    difficulty: 'easy',
    department: 'Loire-Atlantique',
    putInLat: 47.3395,
    putInLng: -1.5260,
    putInDescription: 'Sucé-sur-Erdre — port',
    takeOutLat: 47.4396,
    takeOutLng: -1.4984,
    takeOutDescription: 'Nort-sur-Erdre — quai',
    distanceKm: 14,
    bestSeasonNotes: 'All year',
    description: 'Continuation of the Erdre upstream. Wider, lake-like sections with châteaux.',
  },
  {
    name: 'Canal de Nantes à Brest — Blain section',
    waterway: 'Canal de Nantes à Brest',
    type: 'canal',
    difficulty: 'easy',
    department: 'Loire-Atlantique',
    putInLat: 47.4730,
    putInLng: -1.7660,
    putInDescription: 'Blain — port du canal',
    takeOutLat: 47.5270,
    takeOutLng: -1.8240,
    takeOutDescription: 'Guenrouët — écluse',
    distanceKm: 10,
    bestSeasonNotes: 'All year',
    description: 'Dead-flat canal with lock-keepers. Beautiful tree-lined towpath for shuttle.',
  },
  {
    name: 'Lac de Grand-Lieu shoreline',
    waterway: 'Grand-Lieu',
    type: 'river',
    difficulty: 'moderate',
    department: 'Loire-Atlantique',
    putInLat: 47.0847,
    putInLng: -1.6580,
    putInDescription: 'Passay — observatoire (seasonal access)',
    takeOutLat: 47.0847,
    takeOutLng: -1.6580,
    takeOutDescription: 'Passay — observatoire (loop)',
    distanceKm: 8,
    bestSeasonNotes: 'July to September (restricted access)',
    description: 'France\'s largest natural plain lake. Nature reserve — check access rules before going.',
  },
  {
    name: 'Sèvre Nantaise — Clisson to Vertou',
    waterway: 'Sèvre Nantaise',
    type: 'river',
    difficulty: 'moderate',
    department: 'Loire-Atlantique',
    putInLat: 47.0870,
    putInLng: -1.2820,
    putInDescription: 'Clisson — pont de la Ville',
    takeOutLat: 47.1682,
    takeOutLng: -1.4690,
    takeOutDescription: 'Vertou — chaussée des Moines',
    distanceKm: 22,
    bestSeasonNotes: 'April to September',
    description: 'Scenic river through Clisson\'s Italianate landscape. Some current, minor rapids in places.',
  },
  {
    name: 'Loire — Champtoceaux meander',
    waterway: 'Loire',
    type: 'river',
    difficulty: 'moderate',
    department: 'Loire-Atlantique',
    putInLat: 47.3381,
    putInLng: -1.2690,
    putInDescription: 'Champtoceaux — cale de la Loire',
    takeOutLat: 47.2960,
    takeOutLng: -1.2920,
    takeOutDescription: 'Drain — cale',
    distanceKm: 10,
    bestSeasonNotes: 'June to September',
    description: 'Loire paddling at its most accessible. Stay near banks, watch for barges. Moderate current.',
  },

  // ── Maine-et-Loire ──
  {
    name: 'Mayenne — Château-Gontier to Daon',
    waterway: 'Mayenne',
    type: 'river',
    difficulty: 'easy',
    department: 'Maine-et-Loire',
    putInLat: 47.8275,
    putInLng: -0.6560,
    putInDescription: 'Château-Gontier — base nautique',
    takeOutLat: 47.7640,
    takeOutLng: -0.6310,
    takeOutDescription: 'Daon — cale du port',
    distanceKm: 12,
    bestSeasonNotes: 'April to October',
    description: 'Canalised Mayenne — very gentle. Lock passages possible with portage.',
  },
  {
    name: 'Mayenne — Angers to Grez-Neuville',
    waterway: 'Mayenne',
    type: 'river',
    difficulty: 'easy',
    department: 'Maine-et-Loire',
    putInLat: 47.4784,
    putInLng: -0.5632,
    putInDescription: 'Angers — quai de la Savatte',
    takeOutLat: 47.5990,
    takeOutLng: -0.5470,
    takeOutDescription: 'Grez-Neuville — halte nautique',
    distanceKm: 18,
    bestSeasonNotes: 'All year',
    description: 'The Mayenne below Angers — wide, calm, and well-serviced with landings.',
  },
  {
    name: 'Layon — Beaulieu to Chalonnes',
    waterway: 'Layon',
    type: 'river',
    difficulty: 'easy',
    department: 'Maine-et-Loire',
    putInLat: 47.2730,
    putInLng: -0.5600,
    putInDescription: 'Beaulieu-sur-Layon — pont',
    takeOutLat: 47.3508,
    takeOutLng: -0.7640,
    takeOutDescription: 'Chalonnes-sur-Loire — confluence Loire',
    distanceKm: 20,
    bestSeasonNotes: 'April to September',
    description: 'Vineyard river flowing to the Loire. Mostly calm, a few shallow sections.',
  },
  {
    name: 'Thouet — Montreuil-Bellay to Saumur',
    waterway: 'Thouet',
    type: 'river',
    difficulty: 'easy',
    department: 'Maine-et-Loire',
    putInLat: 47.1303,
    putInLng: -0.1524,
    putInDescription: 'Montreuil-Bellay — base nautique',
    takeOutLat: 47.2548,
    takeOutLng: -0.0766,
    takeOutDescription: 'Saumur — quai de la Loire',
    distanceKm: 22,
    bestSeasonNotes: 'April to September',
    hubeauStationCode: 'L5300010',
    description: 'Gentle Thouet through troglodyte country. Castle views, flat water.',
  },
  {
    name: 'Loire — Saumur islands',
    waterway: 'Loire',
    type: 'river',
    difficulty: 'moderate',
    department: 'Maine-et-Loire',
    putInLat: 47.2640,
    putInLng: -0.0980,
    putInDescription: 'Saumur — cale aval du pont Cessart',
    takeOutLat: 47.2568,
    takeOutLng: -0.1390,
    takeOutDescription: 'Saumur — île Offard',
    distanceKm: 6,
    bestSeasonNotes: 'June to September',
    description: 'Short Loire loop around sand islands. Moderate current, check levels before going.',
  },

  // ── Vienne ──
  {
    name: 'Clain — Poitiers to Ligugé',
    waterway: 'Clain',
    type: 'river',
    difficulty: 'easy',
    department: 'Vienne',
    putInLat: 46.5810,
    putInLng: 0.3407,
    putInDescription: 'Poitiers — parc de Blossac',
    takeOutLat: 46.5300,
    takeOutLng: 0.3260,
    takeOutDescription: 'Ligugé — pont',
    distanceKm: 8,
    bestSeasonNotes: 'April to September',
    hubeauStationCode: 'L4100010',
    description: 'Urban-to-rural section of the Clain. Calm flow, easy access from central Poitiers.',
  },
  {
    name: 'Clain — Vivonne section',
    waterway: 'Clain',
    type: 'river',
    difficulty: 'easy',
    department: 'Vienne',
    putInLat: 46.4298,
    putInLng: 0.2637,
    putInDescription: 'Vivonne — base de loisirs',
    takeOutLat: 46.4800,
    takeOutLng: 0.3000,
    takeOutDescription: 'Marçay — pont',
    distanceKm: 10,
    bestSeasonNotes: 'April to September',
    description: 'Upstream Clain through limestone country. Gentle gradient, rural scenery.',
  },
  {
    name: 'Vienne — Châtellerault',
    waterway: 'Vienne',
    type: 'river',
    difficulty: 'moderate',
    department: 'Vienne',
    putInLat: 46.8162,
    putInLng: 0.5479,
    putInDescription: 'Châtellerault — cale en amont du pont Henri IV',
    takeOutLat: 46.7640,
    takeOutLng: 0.5200,
    takeOutDescription: 'Naintré — cale',
    distanceKm: 10,
    bestSeasonNotes: 'April to September',
    hubeauStationCode: 'L4400010',
    description: 'The Vienne at Châtellerault. Moderate current, wider than the Clain.',
  },
  {
    name: 'Dive — Monts-sur-Guesnes to Pas-de-Jeu',
    waterway: 'Dive',
    type: 'river',
    difficulty: 'easy',
    department: 'Vienne',
    putInLat: 47.0200,
    putInLng: 0.0920,
    putInDescription: 'Monts-sur-Guesnes — pont',
    takeOutLat: 46.9700,
    takeOutLng: 0.0600,
    takeOutDescription: 'Pas-de-Jeu — pont',
    distanceKm: 8,
    bestSeasonNotes: 'April to August',
    description: 'Small tributary, navigable in spring. Very quiet, almost no other boats.',
  },

  // ── Additional Deux-Sèvres ──
  {
    name: 'Sèvre Niortaise — Magné to Coulon',
    waterway: 'Sèvre Niortaise',
    type: 'river',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.3078,
    putInLng: -0.5350,
    putInDescription: 'Magné — embarcadère',
    takeOutLat: 46.3211,
    takeOutLng: -0.5843,
    takeOutDescription: 'Coulon — embarcadère principal',
    distanceKm: 6,
    bestSeasonNotes: 'April to October',
    hubeauStationCode: 'L8100010',
    description: 'Short section linking Magné to the heart of the Green Venice.',
  },
  {
    name: 'Thouet — Parthenay section',
    waterway: 'Thouet',
    type: 'river',
    difficulty: 'moderate',
    department: 'Deux-Sèvres',
    putInLat: 46.6490,
    putInLng: -0.2500,
    putInDescription: 'Parthenay — pont Saint-Jacques',
    takeOutLat: 46.5900,
    takeOutLng: -0.2200,
    takeOutDescription: 'Le Tallud — pont',
    distanceKm: 10,
    bestSeasonNotes: 'April to August',
    description: 'The Thouet through medieval Parthenay. Some current after rain.',
  },
  {
    name: 'Mignon — Mauzé-sur-le-Mignon',
    waterway: 'Mignon',
    type: 'river',
    difficulty: 'easy',
    department: 'Deux-Sèvres',
    putInLat: 46.1990,
    putInLng: -0.6650,
    putInDescription: 'Mauzé-sur-le-Mignon — pont du centre',
    takeOutLat: 46.2350,
    takeOutLng: -0.6900,
    takeOutDescription: 'Prin-Deyrançon — pont',
    distanceKm: 6,
    bestSeasonNotes: 'April to September',
    description: 'Small Marais feeder river. Flat and sheltered, ideal for beginners.',
  },

  // ── Additional Charente ──
  {
    name: 'Charente — Mansle to Aunac',
    waterway: 'Charente',
    type: 'river',
    difficulty: 'easy',
    department: 'Charente',
    putInLat: 45.8740,
    putInLng: 0.1770,
    putInDescription: 'Mansle — base de canoë',
    takeOutLat: 45.9200,
    takeOutLng: 0.1400,
    takeOutDescription: 'Aunac — pont',
    distanceKm: 10,
    bestSeasonNotes: 'April to September',
    description: 'Upper Charente — narrower, greener, fewer boats.',
  },
  {
    name: 'Tardoire — La Rochefoucauld',
    waterway: 'Tardoire',
    type: 'river',
    difficulty: 'moderate',
    department: 'Charente',
    putInLat: 45.7400,
    putInLng: 0.3900,
    putInDescription: 'La Rochefoucauld — pont du château',
    takeOutLat: 45.7080,
    takeOutLng: 0.3400,
    takeOutDescription: 'Rivières — pont',
    distanceKm: 8,
    bestSeasonNotes: 'April to July',
    description: 'Charente tributary with castle backdrop. Moderate flow, scenic gorge section.',
  },

  // ── Additional Loire-Atlantique ──
  {
    name: 'Canal de la Martinière',
    waterway: 'Canal de la Martinière',
    type: 'canal',
    difficulty: 'easy',
    department: 'Loire-Atlantique',
    putInLat: 47.1970,
    putInLng: -1.7720,
    putInDescription: 'Frossay — écluse de la Martinière',
    takeOutLat: 47.2050,
    takeOutLng: -1.9150,
    takeOutDescription: 'Paimboeuf — bassin',
    distanceKm: 15,
    bestSeasonNotes: 'All year',
    description: 'Dead-flat canal parallel to the Loire estuary. No current, sheltered from wind.',
  },

  // ── Additional Vendée ──
  {
    name: 'Vie — Apremont barrage',
    waterway: 'Vie',
    type: 'river',
    difficulty: 'easy',
    department: 'Vendée',
    putInLat: 46.7540,
    putInLng: -1.7450,
    putInDescription: 'Apremont — base de loisirs du lac',
    takeOutLat: 46.7540,
    takeOutLng: -1.7450,
    takeOutDescription: 'Apremont — base de loisirs (loop)',
    distanceKm: 6,
    bestSeasonNotes: 'May to September',
    description: 'Lake formed by the Apremont dam. No current, castle ruins on the shore.',
  },

  // ── Additional Maine-et-Loire ──
  {
    name: 'Maine — Angers city paddle',
    waterway: 'Maine',
    type: 'river',
    difficulty: 'easy',
    department: 'Maine-et-Loire',
    putInLat: 47.4732,
    putInLng: -0.5540,
    putInDescription: 'Angers — quai Ligny',
    takeOutLat: 47.4600,
    takeOutLng: -0.5700,
    takeOutDescription: 'Angers — Île Saint-Aubin',
    distanceKm: 5,
    bestSeasonNotes: 'All year',
    description: 'Short paddle from the château along the Maine. Flat, views of the castle walls.',
  },
]

// ──────────────────────────────────────────────
// Main seeding function
// ──────────────────────────────────────────────
async function main() {
  console.log(`Seeding ${CURATED_ROUTES.length} curated flat-water routes...`)

  let created = 0
  let skipped = 0

  for (const route of CURATED_ROUTES) {
    // Skip if already exists by name
    const existing = await prisma.route.findFirst({
      where: { name: route.name },
    })

    if (existing) {
      console.log(`  ⏭  Skip (exists): ${route.name}`)
      skipped++
      continue
    }

    // Build simple GeoJSON LineString from put-in to take-out
    const geojson = {
      type: 'Feature' as const,
      properties: {
        name: route.name,
        waterway: route.waterway,
        department: route.department,
      },
      geometry: {
        type: 'LineString' as const,
        coordinates: [
          [route.putInLng, route.putInLat],
          [route.takeOutLng, route.takeOutLat],
        ],
      },
    }

    await prisma.route.create({
      data: {
        name: route.name,
        description: route.description || null,
        type: route.type,
        difficulty: route.difficulty,
        distanceKm: route.distanceKm,
        putInLat: route.putInLat,
        putInLng: route.putInLng,
        putInDescription: route.putInDescription,
        takeOutLat: route.takeOutLat,
        takeOutLng: route.takeOutLng,
        takeOutDescription: route.takeOutDescription,
        bestSeasonNotes: route.bestSeasonNotes,
        hubeauStationCode: route.hubeauStationCode || null,
        geojson,
        createdBy: null,
      },
    })

    console.log(`  ✓  Created: ${route.name}`)
    created++
  }

  console.log(`\nDone! Created ${created}, skipped ${skipped} (already existed).`)
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
